# Decision Tree Regressor

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error,r2_score
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [32]:
df=pd.read_csv("C:/Users/goatt/Downloads/Position_Salaries.csv")
df

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [33]:
X=df.iloc[:,0:1].values
y=df.iloc[:,2].values

In [34]:
X = pd.DataFrame(X, columns=["job"])
X = pd.get_dummies(X, drop_first=True)
X

,job_C-level,job_CEO,job_Country Manager,job_Junior Consultant,job_Manager,job_Partner,job_Region Manager,job_Senior Consultant,job_Senior Partner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,True,False,False,False,False
4,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False,False,True
8,True,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False,False

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.45,random_state=0)

In [36]:
dtr_model=DecisionTreeRegressor(random_state=0)

In [48]:
dtr_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [49]:
y_pred=dtr_model.predict(X_test)

In [50]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
mse,r2

(0.03773584905660377, 0.944327731092437)

# Decision Tree Classifier

In [43]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [45]:
iris=load_iris()
X=iris.data
y=iris.target

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=42)

In [47]:
dtc_model=DecisionTreeClassifier()

In [51]:
dtc_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [52]:
y_pred=dtc_model.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2, 1, 2, 1])

In [55]:
confusion_matrix(y_test,y_pred),recall_score(y_test,y_pred,average="micro"),precision_score(y_test,y_pred,average="micro")

(array([[19,  0,  0],
        [ 0, 17,  0],
        [ 0,  1, 16]]),
 0.9811320754716981,
 0.9811320754716981)

# Decision Tree Criterion

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [61]:
X,y=make_classification(n_samples=1000,n_features=5,random_state=42)

In [62]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
tree_gain=DecisionTreeClassifier(criterion="entropy")

In [64]:
tree_gain.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [65]:
y_pred=tree_gain.predict(X_test)
accuracy_score(y_test,y_pred)

0.815

In [66]:
tree_gini=DecisionTreeClassifier(criterion="gini")
tree_gini.fit(X_train,y_train)

DecisionTreeClassifier()

In [71]:
y_pred=tree_gain.predict(X_test)
accuracy_score(y_test,y_pred)

0.815

In [77]:
tree_gini.tree_.node_count,tree_gain.tree_.node_count

(149, 147)

In [79]:
tree_gini.get_depth(),tree_gain.get_depth()

(11, 12)

# Pruning

In [80]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [81]:
iris=load_iris()
X=iris.data
y=iris.target

In [88]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=42)

In [89]:
clf=DecisionTreeClassifier()

In [90]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [91]:
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9466666666666667

In [92]:
path=clf.cost_complexity_pruning_path(X_train,y_train)

In [93]:
ccp_alphas,impuities=path.ccp_alphas,path.impurities

In [97]:
clfs=[]
for ccp_alpha in ccp_alphas:
    clf=DecisionTreeClassifier(random_state=0,ccp_alpha=ccp_alpha)
    clf.fit(X_train,y_train)
    clfs.append(clf)

In [102]:
clfs=clfs[:-1]

max_accuracy=-1
best_clf=None
for clf in clfs:
    y_pred=clf.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(accuracy)
    if accuracy>max_accuracy:
        max_accuracy=accuracy
        best_clf=clf
print("thebest ",max_accuracy)

0.96
0.9733333333333334
0.9733333333333334
1.0
thebest  1.0